server:
  port: 8080
spring:
  application:
    name: client01
eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true #使用 ip 注册服务而不是使用 hostname
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/