server:
  port: 8081
dubbo:
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    port: 2181
  protocol:
    name: dubbo
    port: 20881
  application:
    name: ${spring.application.name}

spring:
  application:
    name: serviceA