spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username:  #发送邮件的邮箱地址
    password:  #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 25 #465或者994
    from: xxx@163.com # 发送邮件的地址，和上面username一致