spring:
  application:
    name: feign-client
server:
  port: 8034
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  httpclient:
    enabled: false #禁用urlhttpconnection
  okhttp:
    enabled: true #开启okhttp
logging:
  level:
    com.rolex.alphax.service: debug #开启日志