spring:
  application:
    name: spring-boot-jpa
  jpa:
    # 配置 DBMS 类型
    database: MYSQL
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
        # 配置开启自动更新表结构
          auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085
