server:
  port: 8080
  servlet:
    session:
      timeout: 1m
      cookie:
        http-only: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=GMT%2B8&useUnicode=true&ampcharacterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    login-return-type: html
#    user:
#      name: john
#      password: 123
logging:
  level:
    com.rolex.alphax: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/ #调整页面路径
    enabled: true

