package com.rolex.tips.entity;

import lombok.Data;

@Data
public class TagMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.user_id
     *
     * @mbggenerated Mon Jul 04 15:40:58 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_id
     *
     * @mbggenerated Mon Jul 04 15:40:58 CST 2022
     */
    private Integer tagId;

}