spring:
  application:
    name: rabbitmq
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
      direct:
        acknowledge-mode: manual
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


server:
  port: 0